In [ ]:
import numpy
arr = numpy.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [18]:
import numpy
arr = numpy.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [19]:
import numpy
arr = numpy.array([[1,2],[3,4]])
print(arr)

[[1 2]
 [3 4]]


In [20]:
import numpy
arr = numpy.array([[[1,2,3],[4,5,6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]]


In [12]:
import numpy as np
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3],[4, 5, 6]])
d = np.array([[[1,2,3],[3,4,5]],[[5,6,7],[8,9,10]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [5]:
import numpy as np
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimension :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimension : 5


In [19]:
import numpy as np
arr = np.array([1, 2, 3, 4])
print(arr[0])
print(arr[1])

1
2


In [20]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr[2] + arr[3])

7


In [22]:
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('2nd element on 1st row:', arr[0, 1])

2nd element on 1st row: 2


In [23]:
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('5th element on 2nd row:', arr[1, 4])

5th element on 2nd row: 10


In [27]:
import numpy as np

arr = np.array([
    [[1,2,3], [4,5,6]],
    [[7,8,9], [10,11,12]]
])

print(arr[0,1,2])


6


In [28]:
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('Last element on 2nd dim:', arr[1, -1])

Last element on 2nd dim: 10


In [6]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr[1:5])

[2 3 4 5]


In [9]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr[4:])

[5 6 7]


In [14]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr[:4])

[1 2 3 4]


In [15]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr[-3:-1])


[5 6]


In [18]:
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1, 1:4])

[7 8 9]


In [29]:
import numpy as np
arr = np.array(['apple', 'banana', 'cherry'])
print(arr.dtype)

<U6


In [30]:
import numpy as np
arr = np.array([1,2,3,4,5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [31]:
import numpy as np
arr = np.array([1,2,3,4,5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [32]:
import numpy as np
arr = np.array([1,2,3,4,5])
x = arr.view()
arr[0] = 31

print(arr)
print(x)

[31  2  3  4  5]
[31  2  3  4  5]


In [33]:
import numpy as np
arr = np.array([1,2,3,4,5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


In [1]:
import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr.shape)

(2, 4)


In [3]:
import numpy as np
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('Shape of array:', arr.shape)

[[[[[1 2 3 4]]]]]
Shape of array: (1, 1, 1, 1, 4)


In [10]:
import numpy as np

arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [11]:
import numpy as np

arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

newarr = arr.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [13]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])

newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6]


In [15]:
import numpy as np
arr = np.array([1,2,3])
for x in arr:
    print(x)

1
2
3


In [16]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
for x in arr:
    print(x)

[1 2 3]
[4 5 6]


In [17]:
import numpy as np
arr = np.array([[[1,2,3],[3,4,5]],[[5,6,7],[8,9,10]]])
for x in arr:
    for y in x:
        for z in y:
            print(z)

1
2
3
3
4
5
5
6
7
8
9
10


In [18]:
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

arr = np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


In [21]:
import numpy as np
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])

arr = np.concatenate((arr1,arr2), axis=1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [1]:
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

arr = np.stack((arr1,arr2), axis=0)
print(arr)

[[1 2 3]
 [4 5 6]]


In [2]:
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

arr = np.hstack((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


In [4]:
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

arr = np.vstack((arr1,arr2))
print(arr)

[[1 2 3]
 [4 5 6]]


In [5]:
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

arr = np.dstack((arr1,arr2))
print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


In [9]:
import numpy as np
arr = np.array([1,2,3,4,5,6])
newarr = np.array_split(arr,3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [10]:
import numpy as np
arr = np.array([1,2,3,4,5,6])
newarr = np.array_split(arr,4)
print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [11]:
import numpy as np
arr = np.array([1,2,3,4,5,6])
newarr = np.array_split(arr,3)
print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5 6]


In [13]:
import numpy as np

arr = np.array([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]])
newarr = np.array_split(arr, 3)

print(newarr)


[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [16]:
import numpy as np

arr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
newarr = np.hsplit(arr, 3)

print(newarr)


[array([[ 1],
       [ 4],
       [ 7],
       [10]]), array([[ 2],
       [ 5],
       [ 8],
       [11]]), array([[ 3],
       [ 6],
       [ 9],
       [12]])]
