In [128]:
import numpy as np
#1 Create an empty and full NumPy array
arr1 = np.array([])
arr2 = np.array([1,2,3])

print(arr1)
print(arr2)

[]
[1 2 3]


In [ ]:
#2 Create a Numpy array filled with all zeros
arr = np.zeros(4, dtype=int)
print(arr)

[0 0 0 0]


In [ ]:
#3 Create a Numpy array filled with all ones
arr = np.ones(4, dtype=int)
print(arr)

[1 1 1 1]


In [ ]:
#4 Check whether a Numpy array contains a specified row
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

row = np.array([4, 5, 6])

exists = np.any(np.all(arr == row, axis=1))
print(exists)

True


In [13]:
#5 Remove rows in Numpy array that contains non-numeric values
import numpy as np

arr = np.array([["10", "20", "30"],
                ["40", "x",  "60"],
                ["70", "80", "90"]])

clean_rows = []

for row in arr:
    try:
        clean_rows.append(row.astype(float))
    except ValueError:
        pass   # skip rows with non-numeric values

clean_arr = np.array(clean_rows)
print(clean_arr)


[[10. 20. 30.]
 [70. 80. 90.]]


In [ ]:
#6 Remove single-dimensional entries from shape of an array
np.squeeze(np.array([[[1,2,3]]]))

array([1, 2, 3])

In [20]:
#7 Find number of occurrences of a sequence
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9],
                [4, 5, 6]])

seq = np.array([4, 5, 6])

count = 0
for x in arr:
    if np.all(x == seq):
        count+=1
print(count)

2


In [22]:
#8 Find most frequent value
import numpy as np

arr = np.array([1, 2, 2, 3, 3, 3, 3, 4])

values, counts = np.unique(arr, return_counts=True)

most_frequent = values[np.argmax(counts)]
print(most_frequent)

3


In [ ]:
#9 Combining a one and a two-dimensional
import numpy as np

a = np.array([1, 2, 3])
b = np.array([[4, 5, 6], [7, 8, 9]])

result = np.vstack([a, b])
print(result)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [32]:
#10 Build an array of all combinations of two NumPy arrays
a = np.array([1,2])
b = np.array([3,4])
comb = np.array(np.meshgrid(a,b)).T.reshape(-1,2)
print(comb)

[[1 3]
 [1 4]
 [2 3]
 [2 4]]


In [36]:
#11 Add a border around a NumPy array
arr = np.ones((3,3))
bordered = np.pad(arr, pad_width=1)
print(bordered)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [39]:
#12 Compare two NumPy arrays
arr1 = np.array([12,3,3,4])
arr2 = np.array([34, 42, 42])
np.array_equal(arr1, arr2)

False

In [40]:
#13 Check whether specified values are present in NumPy array
arr = np.array([1,2,23,42,4])
np.isin([2,5], arr)

array([ True, False])

In [48]:
#14 Get 2D diagonals of a 3D array
arr = np.arange(27).reshape(3,3,3)

print(arr)
diagonals = np.diagonal(arr, axis1=1, axis2=2)

print("\n2D diagonals:\n",diagonals)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]

2D diagonals:
 [[ 0  4  8]
 [ 9 13 17]
 [18 22 26]]


In [51]:
#15 Flatten a 2d array into 1d array
arr = np.array([[1,2],[3,4]])
arr1 = arr.flatten()
print(arr1)

[1 2 3 4]


In [56]:
#16 Move axes of an array to new positions
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
newarr = np.moveaxis(arr, 0, 2)
print(newarr)

[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


In [57]:
#17 Interchange two axes of an array
arr.swapaxes(0,1)
print(arr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [60]:
#18 Fibonacci Series using Binet Formula
n = 10
phi = (1 + 5**0.5)/2
fib = np.array([int((phi**i - (-phi)**(-i))/np.sqrt(5)) for i in range(n)])
print(fib)

[ 0  1  1  2  3  5  8 13 21 34]


In [62]:
#19 Counts number of non-zero values
arr = np.array([1,2,3,0,3,0])
np.count_nonzero(arr)

np.int64(4)

In [71]:
#20 Count number of elements along a given axis
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

print(arr.shape[0])
print(arr.shape[1])

3
4


In [76]:
#21 Trim leading and/or trailing zeros from a 1-D array
temp = np.array([0,0,1,2,0,3,0])
arr = np.trim_zeros(temp)
print(temp)
print(arr)

[0 0 1 2 0 3 0]
[1 2 0 3]


In [79]:
#22 Change data type of given numpy array
arr = np.array(['1','2.2','0'])
newarr =  arr.astype(float)
print(newarr)

[1.  2.2 0. ]


In [80]:
#23 Reverse a numpy array
arr = np.array([0,0,1,2,0,3,0])
newarr = arr[::-1]
print(newarr)

[0 3 0 2 1 0 0]


In [83]:
#24 Make a NumPy array read-only
lockedArr = np.array([1,2,3,4,5])
lockedArr.flags.writeable = False
# lockedArr[0] = 11
print(lockedArr)

[1 2 3 4 5]


In [89]:
#25 Sum of All Elements in a Numpy Array
arr = np.array([1,2,3,4])
print(arr.sum())

10


In [91]:
#26 Maximum Element in a Numpy Array
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])
print(arr.max())

12


In [93]:
#27 Mean of a Numpy Array
arr = np.array([1, 2, 3, 4])
print(arr.mean())

2.5


In [94]:
#28 Reshape a Numpy Array
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])
print(arr.reshape(2,6))

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [95]:
#29 Standard Deviation
arr = np.array([1, 2, 3, 4])
print(arr.std())

1.118033988749895


In [97]:
#30 Element-wise Exponentiation
arr = np.array([1, 2, 3, 4])
print(np.power(arr, 2))

[ 1  4  9 16]


In [99]:
#31 Array Concatenation
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

arr3 = np.concatenate((arr1,arr2), axis = 0)
print(arr3)

[1 2 3 4 5 6]


In [102]:
#32 Reverse Rows of a 2D Array
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])
arr[::, ::-1]

array([[ 4,  3,  2,  1],
       [ 8,  7,  6,  5],
       [12, 11, 10,  9]])

In [ ]:
#33 Diagonal Elements in an Array
np.diagonal(arr)

array([ 1,  6, 11])

In [ ]:
#34 3D Array from a List of Lists
arr = np.array([[[1,2],[3,4]], [[5,6],[7,8]]])
print(arr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [109]:
#35 Accessing Element in a 3D Array
print(arr[1,0,1])

6


In [ ]:
#36 Maximum Element along Each Axses in a 3D Array
arr = np.array([[[1,2],[3,4]], [[5,6],[7,8]]])
print(arr.max(axis=0))
print(arr.max(axis=1))
print(arr.max(axis=2))

[[5 6]
 [7 8]]
[[3 4]
 [7 8]]
[[2 4]
 [6 8]]


In [120]:
#37 slice a 3D Array
arr = np.array([
    [[ 1,  2,  3],
     [ 4,  5,  6]],

    [[ 7,  8,  9],
     [10, 11, 12]],

    [[13, 14, 15],
     [16, 17, 18]]
])

newarr = arr[0:2, 0:2, 0:2]
print(newarr)

[[[ 1  2]
  [ 4  5]]

 [[ 7  8]
  [10 11]]]


In [121]:
#38 Flatten a 3D Array
arr = np.array([
    [[1, 2, 3],
     [4, 5, 6]],

    [[7, 8, 9],
     [10,11,12]]
])

flat = arr.flatten()
print(flat)


[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [126]:
#39 Replace array elements that doesn’t satisfy given condition
arr = np.array([1,2,3,4,15,2,67,7])
arr[arr < 5] = -5
print(arr)

[-5 -5 -5 -5 15 -5 67  7]


In [127]:
#40 Return indices of elements where given condition is satisfied
arr = np.array([1,2,3,4,15,2,67,7])
print(np.where(arr > 5))

(array([4, 6, 7]),)


In [132]:
#41 Replace NaN values with average of columns
arr = np.array([[1,np.nan,3],[4,1,6]])
col_mean = np.nanmean(arr, axis=0)
inds = np.where(np.isnan(arr))
arr[inds] = np.take(col_mean, inds[1])
print(arr)

[[1. 1. 3.]
 [4. 1. 6.]]


In [133]:
#42 Replace negative value with zero
arr = np.array([-1,2,-3,4])
arr[arr < 0] = 0
print(arr)

[0 2 0 4]


In [136]:
#43 Get values of an NumPy array at certain index positions
arr = np.array([10,20,30,40,50])
vals = np.take(arr, [1,3])
print(vals)

[20 40]


In [137]:
#44 Find indices of elements equal to zero in an array
arr = np.array([0,1,0,2,3])
idx = np.where(arr == 0)
print(idx)

(array([0, 2]),)


In [141]:
#45 Remove columns in array that contains non-numeric values
arr = np.array([
    [1, 2, "x"],
    [4, 5, 6],
    [7, "y", 9]
], dtype=object)

good_cols = []

for j in range(arr.shape[1]):
    flag = True
    for x in arr[:, j]:
        if not isinstance(x, (int, float, np.number)):
            flag = False
            break
    if flag:
        good_cols.append(j)

newarr = arr[:, good_cols]
print(newarr)


[[1]
 [4]
 [7]]


In [142]:
#46 Access different rows of a multidimensional array
arr = np.array([[1,2],[3,4],[5,6]])
rows = arr[[0,2]]
print(rows)

[[1 2]
 [5 6]]


In [143]:
#47 Compute median of the flattened NumPy array
arr = np.array([[1,3],[2,4]])
med = np.median(arr.ravel())
print(med)

2.5


In [145]:
#48 Find Mean of a List of Numpy Array
lst = [np.array([1,2,3]), np.array([4,5,6])]
mean = np.mean(lst, axis=1)
print(mean)

[2. 5.]


In [147]:
#49 Calculate mean of array ignoring NaN value
arr = np.array([1,np.nan,3])
m = np.nanmean(arr)
print(m)

2.0


In [148]:
#50 Compute variance of NumPy array
arr = np.array([1,2,3,4])
v = arr.var()
print(v)

1.25


In [149]:
#51 Compute standard deviation of NumPy array
arr = np.array([1,2,3,4])
s = arr.std()
print(s)

1.118033988749895


In [150]:
#52 Compute pearson product-moment correlation coefficients of two given arrays
a = np.array([1,2,3])
b = np.array([1,5,7])
corr = np.corrcoef(a,b)
print(corr)

[[1.         0.98198051]
 [0.98198051 1.        ]]


In [151]:
#53 Calculate mean across dimension in a 2D NumPy array
arr = np.array([[1,2,3],[4,5,6]])
m = arr.mean(axis=1)
print(m)

[2. 5.]


In [153]:
#54 Calculate average, variance and standard deviation in Python
arr = np.array([1,2,3,4])
avg = np.mean(arr)
var = np.var(arr)
std = np.std(arr)
print("Array:", arr)
print("Average:", avg)
print("Variance:", var)
print("Standard Deviation:", std)

Array: [1 2 3 4]
Average: 2.5
Variance: 1.25
Standard Deviation: 1.118033988749895


In [154]:
#55 Get row numbers of array having element larger than X
arr = np.array([[1,7],[3,4],[9,2]])
rows = np.where(arr > 5)[0]
print(rows)

[0 2]


In [155]:
#56 Get filled diagonals of array
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
np.fill_diagonal(arr, 0)
print(arr)

[[0 2 3]
 [4 0 6]
 [7 8 0]]


In [159]:
#57 Check elements present in an array
arr = np.array([1,2,3,4,5])
res = np.isin(arr, [2,5])
print(res)

[False  True False False  True]


In [160]:
#58 Combined array index by index
a = np.array([1,2,3])
b = np.array([4,5,6])
combined = np.array(list(zip(a,b)))
print(combined)

[[1 4]
 [2 5]
 [3 6]]
